version: '3.3'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    restart: always
    ports:
      - "3100:8080"
  db:
    image: mysql:5.6
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  rabbitmq:
    image: rabbitmq:3.7-alpine
    restart: always
    ports:
      - "5672:5672"
      - "25672:25672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin


  adminer:
    image: adminer
    restart: always
    ports:
      - 8099:8080
