version: "3.3"

services:
  jaeger-all:
    image: jaegertracing/all-in-one:1.8
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
