
version: "3.3"

services:
  elasticsearch:
    image: elasticsearch:5.6-alpine 
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
        - ./data:/usr/share/elasticsearch/data

  kibana: 
    image: kibana:5.6
    ports:
      - "5601:5601"


