version: "3.3"

services:
  tyk-gateway:
    container_name: tyk-gateway
    image: tykio/tyk-gateway:v2.6.1
    restart: unless-stopped
    ports:
    - 8811:8080
    extra_hosts:
      - "tyk-redis.nexusguard.net:172.17.0.1"
    volumes:
    - ./tyk-gateway-docker/tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
    - ./apps:/opt/tyk-gateway/apps
    networks:
    - tyk-network
  tyk-redis:
    container_name: tyk-redis
    image: redis:4.0-alpine
    ports:
    - 6390:6379
    networks:
      - tyk-network

networks:
  tyk-network: