version: '3.3'

services:
  zookeeper:
    image: zookeeper:3.5.5
    restart: unless-stopped.
    hostname: zoo1
    ports:
    - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    restart: unless-stopped
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stream-in:1:1,stream-out:1:1"
    depends_on:
    - zookeeper

#  kafka1:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
#      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
#      KAFKA_BROKER_ID: 1
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_CREATE_TOPICS: "stream-in:2:1,stream-out:2:1"
#    depends_on:
#      - zookeeper
#    container_name: kafka1
#
#
#  kafka2:
#    image: wurstmeister/kafka
#    ports:
#      - "9093:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 10.6.5.162
#      KAFKA_ADVERTISED_PORT: 9093
#      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
#      KAFKA_BROKER_ID: 2
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    depends_on:
#      - zookeeper
#    container_name: kafka2
